# Generated by Django 4.2.30 on 2026-08-17 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(choices=[('TEMPERATURE', 'Température'), ('PRECIPITATION', 'Précipitations'), ('HUMIDITY', 'Humidité'), ('WIND_SPEED', 'Vitesse du vent'), ('WIND_DIRECTION', 'Direction du vent'), ('PRESSURE', 'Pression'), ('RADIATION', 'Rayonnement solaire')], max_length=32)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('baseline_value', models.FloatField(blank=True, null=True)),
                ('std_dev', models.FloatField(blank=True, null=True)),
                ('observed_at', models.DateTimeField()),
                ('source', models.CharField(default='NASA POWER', max_length=128)),
                ('is_simulated', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_observations', to='geography.monitoringzone')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['zone', 'variable', '-observed_at'], name='climate_cli_zone_id_32d88f_idx')],
            },
        ),
    ]
