# Generated by Django 4.2.30 on 2026-08-17 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEGRADED', 'Dégradée'), ('OFFLINE', 'Hors ligne')], default='ACTIVE', max_length=20)),
                ('is_simulated', models.BooleanField(default=True)),
                ('battery_level', models.IntegerField(default=100)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='geography.monitoringzone')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('TEMPERATURE', 'Température'), ('PH', 'pH'), ('TURBIDITY', 'Turbidité'), ('CONDUCTIVITY', 'Conductivité'), ('DISSOLVED_OXYGEN', 'Oxygène dissous'), ('WATER_LEVEL', "Niveau d'eau"), ('NO2', 'NO₂'), ('PM25', 'PM2.5'), ('PM10', 'PM10')], max_length=32)),
                ('code', models.CharField(max_length=128)),
                ('unit', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='sensors.monitoringstation')),
            ],
            options={
                'unique_together': {('station', 'sensor_type', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('recorded_at', models.DateTimeField()),
                ('quality', models.CharField(default='GOOD', max_length=32)),
                ('is_simulated', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensor')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['sensor', '-recorded_at'], name='sensors_sen_sensor__784af1_idx')],
            },
        ),
    ]
