# Generated by Django 4.2.30 on 2026-08-17 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satellite', models.CharField(choices=[('SENTINEL2', 'Sentinel-2'), ('SENTINEL1', 'Sentinel-1'), ('SENTINEL5P', 'Sentinel-5P'), ('LANDSAT8', 'Landsat 8'), ('LANDSAT9', 'Landsat 9')], max_length=32)),
                ('product_type', models.CharField(blank=True, choices=[('L2A', 'Level-2A'), ('L1C', 'Level-1C'), ('TOA', 'Top of Atmosphere')], max_length=16)),
                ('acquisition_time', models.DateTimeField()),
                ('cloud_cover', models.FloatField(default=0.0)),
                ('source', models.CharField(default='Copernicus', max_length=128)),
                ('is_simulated', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satellite_observations', to='geography.monitoringzone')),
            ],
            options={
                'ordering': ['-acquisition_time'],
            },
        ),
    ]
