from django.core.management.base import BaseCommand
from apps.geography.models import Country, Region, RegionalDirectorate, MonitoringZone

class Command(BaseCommand):
    help = "Seed official 19 Administrative Regions of Mali (+ Bamako District) and Regional Directorates (DRPC, DRH, DREF, DRACPN, DRA)."

    def handle(self, *args, **options):
        self.stdout.write(self.style.NOTICE("=== DÉBUT DU SEEDING GÉOGRAPHIQUE MALI (Loi 2023) ==="))

        country, _ = Country.objects.get_or_create(
            code="MLI",
            defaults={"name": "Mali"}
        )

        # 1. 19 Régions Administratives officielles + District de Bamako
        # (Loi n° 2023-006 du 13 mars 2023 portant création des circonscriptions administratives en République du Mali)
        regions_catalog = [
            {
                "region_number": 0,
                "name": "District de Bamako",
                "code": "BKO",
                "capital": "Bamako",
                "latitude": 12.6392,
                "longitude": -8.0029,
                "area_km2": 252.0,
                "population": 2800000,
            },
            {
                "region_number": 1,
                "name": "Kayes",
                "code": "KAY",
                "capital": "Kayes",
                "latitude": 14.4469,
                "longitude": -11.4445,
                "area_km2": 61258.0,
                "population": 1400000,
            },
            {
                "region_number": 2,
                "name": "Koulikoro",
                "code": "KOU",
                "capital": "Koulikoro",
                "latitude": 12.8627,
                "longitude": -7.5599,
                "area_km2": 45000.0,
                "population": 1800000,
            },
            {
                "region_number": 3,
                "name": "Sikasso",
                "code": "SIK",
                "capital": "Sikasso",
                "latitude": 11.3176,
                "longitude": -5.6665,
                "area_km2": 40000.0,
                "population": 2100000,
            },
            {
                "region_number": 4,
                "name": "Ségou",
                "code": "SEG",
                "capital": "Ségou",
                "latitude": 13.4317,
                "longitude": -6.2157,
                "area_km2": 50000.0,
                "population": 2300000,
            },
            {
                "region_number": 5,
                "name": "Mopti",
                "code": "MOP",
                "capital": "Mopti",
                "latitude": 14.4961,
                "longitude": -4.1844,
                "area_km2": 45000.0,
                "population": 1500000,
            },
            {
                "region_number": 6,
                "name": "Tombouctou",
                "code": "TOM",
                "capital": "Tombouctou",
                "latitude": 16.7666,
                "longitude": -3.0026,
                "area_km2": 200000.0,
                "population": 700000,
            },
            {
                "region_number": 7,
                "name": "Gao",
                "code": "GAO",
                "capital": "Gao",
                "latitude": 16.2717,
                "longitude": -0.0447,
                "area_km2": 100000.0,
                "population": 600000,
            },
            {
                "region_number": 8,
                "name": "Kidal",
                "code": "KID",
                "capital": "Kidal",
                "latitude": 18.4411,
                "longitude": 1.4078,
                "area_km2": 151450.0,
                "population": 80000,
            },
            {
                "region_number": 9,
                "name": "Taoudénit",
                "code": "TAO",
                "capital": "Taoudénit",
                "latitude": 22.6775,
                "longitude": -3.9806,
                "area_km2": 320000.0,
                "population": 25000,
            },
            {
                "region_number": 10,
                "name": "Ménaka",
                "code": "MEN",
                "capital": "Ménaka",
                "latitude": 15.9182,
                "longitude": 2.4022,
                "area_km2": 81000.0,
                "population": 60000,
            },
            {
                "region_number": 11,
                "name": "Nioro du Sahel",
                "code": "NIO",
                "capital": "Nioro",
                "latitude": 15.2281,
                "longitude": -9.5898,
                "area_km2": 23000.0,
                "population": 550000,
            },
            {
                "region_number": 12,
                "name": "Kita",
                "code": "KIT",
                "capital": "Kita",
                "latitude": 13.0349,
                "longitude": -9.4895,
                "area_km2": 35000.0,
                "population": 450000,
            },
            {
                "region_number": 13,
                "name": "Dioïla",
                "code": "DIO",
                "capital": "Dioïla",
                "latitude": 12.4939,
                "longitude": -6.7972,
                "area_km2": 12800.0,
                "population": 500000,
            },
            {
                "region_number": 14,
                "name": "Nara",
                "code": "NAR",
                "capital": "Nara",
                "latitude": 15.1697,
                "longitude": -7.2863,
                "area_km2": 30000.0,
                "population": 300000,
            },
            {
                "region_number": 15,
                "name": "Bougouni",
                "code": "BOU",
                "capital": "Bougouni",
                "latitude": 11.4177,
                "longitude": -7.4832,
                "area_km2": 20000.0,
                "population": 500000,
            },
            {
                "region_number": 16,
                "name": "Koutiala",
                "code": "KTL",
                "capital": "Koutiala",
                "latitude": 12.3917,
                "longitude": -5.4642,
                "area_km2": 18000.0,
                "population": 600000,
            },
            {
                "region_number": 17,
                "name": "San",
                "code": "SAN",
                "capital": "San",
                "latitude": 13.3034,
                "longitude": -4.8956,
                "area_km2": 14000.0,
                "population": 350000,
            },
            {
                "region_number": 18,
                "name": "Douentza",
                "code": "DOU",
                "capital": "Douentza",
                "latitude": 14.9961,
                "longitude": -2.9497,
                "area_km2": 23000.0,
                "population": 250000,
            },
            {
                "region_number": 19,
                "name": "Bandiagara",
                "code": "BAN",
                "capital": "Bandiagara",
                "latitude": 14.3501,
                "longitude": -3.6104,
                "area_km2": 10500.0,
                "population": 320000,
            },
        ]

        regions_by_code = {}
        for r_data in regions_catalog:
            code = r_data["code"]
            # Check if region already exists by code or by name to prevent duplication
            r = Region.objects.filter(code=code).first()
            if not r:
                r = Region.objects.filter(name__iexact=r_data["name"]).first()

            if r:
                r.country = country
                r.name = r_data["name"]
                r.code = code
                r.region_number = r_data["region_number"]
                r.capital = r_data["capital"]
                r.latitude = r_data["latitude"]
                r.longitude = r_data["longitude"]
                r.area_km2 = r_data["area_km2"]
                r.population = r_data["population"]
                r.save()
            else:
                r = Region.objects.create(country=country, **r_data)

            regions_by_code[code] = r
            self.stdout.write(f"  ✓ Région: {r.name} (Code {r.code}, Chef-lieu {r.capital})")

        self.stdout.write(self.style.SUCCESS(f"-> 20 entités régionales synchronisées (19 Régions + Bamako)"))

        # 2. Directions Régionales opérationnelles
        # Focus identifié pour: Bamako, Ségou, Mopti, Kayes, Sikasso, Koulikoro, Gao
        # + DRPC d'urgence 122 pour toutes les régions restantes.
        directorates_catalog = [
            # ── BAMAKO ──
            {
                "region_code": "BKO",
                "directorate_type": "DRPC",
                "name": "Direction Régionale de la Protection Civile du District de Bamako",
                "address": "Zone ACI 2000 / Quartier Hippodrome, Bamako",
                "latitude": 12.6315,
                "longitude": -8.0125,
                "phone_primary": "+223 20 22 26 22",
                "phone_secondary": "+223 20 22 26 23",
                "emergency_number": "122",
                "email": "drpc.bamako@protectioncivile.gouv.ml",
                "notes": "Centre de Traitement des Alertes 122 et Groupement des Sapeurs-Pompiers du District.",
            },
            {
                "region_code": "BKO",
                "directorate_type": "DRH",
                "name": "Direction Régionale de l'Hydraulique de Bamako",
                "address": "DNH Cité Administrative / Darsalam, Bamako",
                "latitude": 12.6510,
                "longitude": -7.9980,
                "phone_primary": "+223 20 22 25 88",
                "phone_secondary": "+223 20 22 41 12",
                "emergency_number": "122",
                "email": "drh.bamako@hydraulique.gouv.ml",
                "notes": "Gestion du réseau hydrologique du fleuve Niger à Bamako et contrôle du débit d'étiage.",
            },
            {
                "region_code": "BKO",
                "directorate_type": "DREF",
                "name": "Direction Régionale des Eaux et Forêts de Bamako",
                "address": "Route du Parc National, Koulouba, Bamako",
                "latitude": 12.6580,
                "longitude": -7.9850,
                "phone_primary": "+223 20 23 34 12",
                "phone_secondary": "+223 20 23 34 15",
                "emergency_number": "122",
                "email": "dref.bamako@eaux-forets.gouv.ml",
                "notes": "Protection de la forêt classée de Koulouba et de la ceinture verte de Bamako.",
            },
            {
                "region_code": "BKO",
                "directorate_type": "DRACPN",
                "name": "Direction Régionale de l'Assainissement et du Contrôle des Pollutions et des Nuisances de Bamako",
                "address": "Quartier du Fleuve, Rue 310, Bamako",
                "latitude": 12.6350,
                "longitude": -8.0050,
                "phone_primary": "+223 20 22 48 90",
                "phone_secondary": "+223 20 22 71 30",
                "emergency_number": "122",
                "email": "dracpn.bamako@environnement.gouv.ml",
                "notes": "Surveillance de la qualité de l'eau du Niger et contrôle des rejets industriels et urbains.",
            },
            {
                "region_code": "BKO",
                "directorate_type": "DRA",
                "name": "Direction Régionale de l'Agriculture de Bamako",
                "address": "Quartier du Fleuve, Bamako",
                "latitude": 12.6370,
                "longitude": -8.0090,
                "phone_primary": "+223 20 22 28 44",
                "phone_secondary": "+223 20 22 55 12",
                "emergency_number": "122",
                "email": "dra.bamako@agriculture.gouv.ml",
                "notes": "Surveillance des ceintures maraîchères périurbaines et de la sécurité alimentaire.",
            },

            # ── SÉGOU ──
            {
                "region_code": "SEG",
                "directorate_type": "DRPC",
                "name": "Direction Régionale de la Protection Civile de Ségou",
                "address": "Quartier Administratif, BP 24, Ségou",
                "latitude": 13.4350,
                "longitude": -6.2200,
                "phone_primary": "+223 21 32 18 77",
                "phone_secondary": "+223 21 32 00 22",
                "emergency_number": "122",
                "email": "drpc.segou@protectioncivile.gouv.ml",
                "notes": "Coordination des secours d'urgence, crues du Niger et feux de brousse en zone Office du Niger.",
            },
            {
                "region_code": "SEG",
                "directorate_type": "DRH",
                "name": "Direction Régionale de l'Hydraulique de Ségou",
                "address": "Quartier Somono, face fleuve Niger, Ségou",
                "latitude": 13.4380,
                "longitude": -6.2120,
                "phone_primary": "+223 21 32 04 15",
                "phone_secondary": "+223 21 32 11 08",
                "emergency_number": "122",
                "email": "drh.segou@hydraulique.gouv.ml",
                "notes": "Surveillance du barrage de Markala, jaugeages limnimétriques et alerte crue plaine du Sahel.",
            },
            {
                "region_code": "SEG",
                "directorate_type": "DREF",
                "name": "Direction Régionale des Eaux et Forêts de Ségou",
                "address": "Avenue de l'An 2000, Ségou",
                "latitude": 13.4290,
                "longitude": -6.2190,
                "phone_primary": "+223 21 32 02 11",
                "phone_secondary": "+223 21 32 08 40",
                "emergency_number": "122",
                "email": "dref.segou@eaux-forets.gouv.ml",
                "notes": "Protection des forêts classées de Ségou et lutte contre la déforestation.",
            },
            {
                "region_code": "SEG",
                "directorate_type": "DRACPN",
                "name": "Direction Régionale de l'Assainissement et du Contrôle des Pollutions et des Nuisances de Ségou",
                "address": "Quartier Angoulême, Ségou",
                "latitude": 13.4270,
                "longitude": -6.2230,
                "phone_primary": "+223 21 32 15 44",
                "phone_secondary": "+223 21 32 15 45",
                "emergency_number": "122",
                "email": "dracpn.segou@environnement.gouv.ml",
                "notes": "Contrôle des pesticides agricoles de l'Office du Niger et salubrité publique.",
            },
            {
                "region_code": "SEG",
                "directorate_type": "DRA",
                "name": "Direction Régionale de l'Agriculture de Ségou",
                "address": "Zone Office du Niger, Route de Markala, Ségou",
                "latitude": 13.4330,
                "longitude": -6.2160,
                "phone_primary": "+223 21 32 03 20",
                "phone_secondary": "+223 21 32 07 65",
                "emergency_number": "122",
                "email": "dra.segou@agriculture.gouv.ml",
                "notes": "Suivi agro-météorologique et résilience des périmètres rizicoles.",
            },

            # ── MOPTI ──
            {
                "region_code": "MOP",
                "directorate_type": "DRPC",
                "name": "Direction Régionale de la Protection Civile de Mopti",
                "address": "Carrefour de Sévaré / Mopti, BP 18",
                "latitude": 14.5290,
                "longitude": -4.1030,
                "phone_primary": "+223 21 42 01 22",
                "phone_secondary": "+223 21 42 02 22",
                "emergency_number": "122",
                "email": "drpc.mopti@protectioncivile.gouv.ml",
                "notes": "Poste de commandement avancé de surveillance des inondations du Delta Intérieur du Niger.",
            },
            {
                "region_code": "MOP",
                "directorate_type": "DRH",
                "name": "Direction Régionale de l'Hydraulique de Mopti",
                "address": "Mopti Digue, Port fluvial",
                "latitude": 14.4980,
                "longitude": -4.1880,
                "phone_primary": "+223 21 42 03 40",
                "phone_secondary": "+223 21 42 08 19",
                "emergency_number": "122",
                "email": "drh.mopti@hydraulique.gouv.ml",
                "notes": "Réseau de stations hydrométriques du Delta Central (confluence Niger-Bani).",
            },
            {
                "region_code": "MOP",
                "directorate_type": "DREF",
                "name": "Direction Régionale des Eaux et Forêts de Mopti",
                "address": "Route Principale Sévaré-Mopti",
                "latitude": 14.5100,
                "longitude": -4.1400,
                "phone_primary": "+223 21 42 02 85",
                "phone_secondary": "+223 21 42 06 14",
                "emergency_number": "122",
                "email": "dref.mopti@eaux-forets.gouv.ml",
                "notes": "Protection de la biodiversité des zones humides RAMSAR et des forêts inondables.",
            },
            {
                "region_code": "MOP",
                "directorate_type": "DRACPN",
                "name": "Direction Régionale de l'Assainissement et du Contrôle des Pollutions et des Nuisances de Mopti",
                "address": "Quartier Gangal, Mopti",
                "latitude": 14.4930,
                "longitude": -4.1920,
                "phone_primary": "+223 21 42 09 11",
                "phone_secondary": "+223 21 42 09 12",
                "emergency_number": "122",
                "email": "dracpn.mopti@environnement.gouv.ml",
                "notes": "Gestion de la salubrité riveraine et de la qualité des eaux de pêche.",
            },
            {
                "region_code": "MOP",
                "directorate_type": "DRA",
                "name": "Direction Régionale de l'Agriculture de Mopti",
                "address": "Quartier Administratif de Sévaré",
                "latitude": 14.5260,
                "longitude": -4.1080,
                "phone_primary": "+223 21 42 05 60",
                "phone_secondary": "+223 21 42 07 88",
                "emergency_number": "122",
                "email": "dra.mopti@agriculture.gouv.ml",
                "notes": "Suivi des plaines de décrue et des cultures submersibles.",
            },

            # ── KAYES ──
            {
                "region_code": "KAY",
                "directorate_type": "DRPC",
                "name": "Direction Régionale de la Protection Civile de Kayes",
                "address": "Quartier Légal Ségou, Kayes",
                "latitude": 14.4510,
                "longitude": -11.4390,
                "phone_primary": "+223 21 52 11 22",
                "phone_secondary": "+223 21 52 12 22",
                "emergency_number": "122",
                "email": "drpc.kayes@protectioncivile.gouv.ml",
                "notes": "Gestion des alertes canicule extrême et des crues du fleuve Sénégal (bassin OMVS).",
            },
            {
                "region_code": "KAY",
                "directorate_type": "DRH",
                "name": "Direction Régionale de l'Hydraulique de Kayes",
                "address": "Quartier Kayes N'Di",
                "latitude": 14.4420,
                "longitude": -11.4510,
                "phone_primary": "+223 21 52 14 05",
                "phone_secondary": "+223 21 52 18 33",
                "emergency_number": "122",
                "email": "drh.kayes@hydraulique.gouv.ml",
                "notes": "Suivi des lâchers des barrages de Manantali et Félou, et stations hydrologiques.",
            },
            {
                "region_code": "KAY",
                "directorate_type": "DREF",
                "name": "Direction Régionale des Eaux et Forêts de Kayes",
                "address": "Quartier Plateau Administratif, Kayes",
                "latitude": 14.4490,
                "longitude": -11.4420,
                "phone_primary": "+223 21 52 13 80",
                "phone_secondary": "+223 21 52 17 00",
                "emergency_number": "122",
                "email": "dref.kayes@eaux-forets.gouv.ml",
                "notes": "Protection de la Réserve de Faune de Bafing et surveillance des feux précoces.",
            },
            {
                "region_code": "KAY",
                "directorate_type": "DRACPN",
                "name": "Direction Régionale de l'Assainissement et du Contrôle des Pollutions et des Nuisances de Kayes",
                "address": "Quartier Légal Ségou, Kayes",
                "latitude": 14.4530,
                "longitude": -11.4360,
                "phone_primary": "+223 21 52 20 18",
                "phone_secondary": "+223 21 52 20 20",
                "emergency_number": "122",
                "email": "dracpn.kayes@environnement.gouv.ml",
                "notes": "Contrôle des pollutions liées aux activités minières et protection des cours d'eau.",
            },
            {
                "region_code": "KAY",
                "directorate_type": "DRA",
                "name": "Direction Régionale de l'Agriculture de Kayes",
                "address": "Quartier Lafiabougou, Kayes",
                "latitude": 14.4440,
                "longitude": -11.4470,
                "phone_primary": "+223 21 52 15 66",
                "phone_secondary": "+223 21 52 19 44",
                "emergency_number": "122",
                "email": "dra.kayes@agriculture.gouv.ml",
                "notes": "Résilience agricole en zone soudano-sahélienne et périmètres maraîchers.",
            },

            # ── SIKASSO ──
            {
                "region_code": "SIK",
                "directorate_type": "DRPC",
                "name": "Direction Régionale de la Protection Civile de Sikasso",
                "address": "Quartier Wayerma II, Sikasso",
                "latitude": 11.3250,
                "longitude": -5.6720,
                "phone_primary": "+223 21 62 02 22",
                "phone_secondary": "+223 21 62 03 22",
                "emergency_number": "122",
                "email": "drpc.sikasso@protectioncivile.gouv.ml",
                "notes": "Protection de la zone soudanienne à haute densité forestière et agricole.",
            },
            {
                "region_code": "SIK",
                "directorate_type": "DRH",
                "name": "Direction Régionale de l'Hydraulique de Sikasso",
                "address": "Quartier Sanoubougou, Sikasso",
                "latitude": 11.3120,
                "longitude": -5.6610,
                "phone_primary": "+223 21 62 05 18",
                "phone_secondary": "+223 21 62 08 90",
                "emergency_number": "122",
                "email": "drh.sikasso@hydraulique.gouv.ml",
                "notes": "Surveillance des affluents fluviaux du bassin du Bani et nappes phréatiques.",
            },
            {
                "region_code": "SIK",
                "directorate_type": "DREF",
                "name": "Direction Régionale des Eaux et Forêts de Sikasso",
                "address": "Quartier Mancourani, Sikasso",
                "latitude": 11.3210,
                "longitude": -5.6690,
                "phone_primary": "+223 21 62 04 33",
                "phone_secondary": "+223 21 62 07 55",
                "emergency_number": "122",
                "email": "dref.sikasso@eaux-forets.gouv.ml",
                "notes": "Gestion du premier réservoir forestier du pays et lutte contre la coupe abusive.",
            },
            {
                "region_code": "SIK",
                "directorate_type": "DRACPN",
                "name": "Direction Régionale de l'Assainissement et du Contrôle des Pollutions et des Nuisances de Sikasso",
                "address": "Quartier Sanoubougou I, Sikasso",
                "latitude": 11.3190,
                "longitude": -5.6640,
                "phone_primary": "+223 21 62 11 02",
                "phone_secondary": "+223 21 62 11 05",
                "emergency_number": "122",
                "email": "dracpn.sikasso@environnement.gouv.ml",
                "notes": "Suivi des effluents agro-industriels cotonniers et contrôle environnemental.",
            },
            {
                "region_code": "SIK",
                "directorate_type": "DRA",
                "name": "Direction Régionale de l'Agriculture de Sikasso",
                "address": "Quartier Administratif, Sikasso",
                "latitude": 11.3180,
                "longitude": -5.6680,
                "phone_primary": "+223 21 62 01 45",
                "phone_secondary": "+223 21 62 06 70",
                "emergency_number": "122",
                "email": "dra.sikasso@agriculture.gouv.ml",
                "notes": "Grenier agricole du Mali : suivi des céréales et de la filière coton.",
            },

            # ── KOULIKORO ──
            {
                "region_code": "KOU",
                "directorate_type": "DRPC",
                "name": "Direction Régionale de la Protection Civile de Koulikoro",
                "address": "Quartier Koulikoro Ba, Koulikoro",
                "latitude": 12.8680,
                "longitude": -7.5640,
                "phone_primary": "+223 21 26 21 22",
                "phone_secondary": "+223 21 26 22 22",
                "emergency_number": "122",
                "email": "drpc.koulikoro@protectioncivile.gouv.ml",
                "notes": "Interventions rapides sur le corridor fluvial Koulikoro-Ségou et carrières.",
            },
            {
                "region_code": "KOU",
                "directorate_type": "DRH",
                "name": "Direction Régionale de l'Hydraulique de Koulikoro",
                "address": "Plateau Administratif, Koulikoro",
                "latitude": 12.8590,
                "longitude": -7.5540,
                "phone_primary": "+223 21 26 23 10",
                "phone_secondary": "+223 21 26 25 44",
                "emergency_number": "122",
                "email": "drh.koulikoro@hydraulique.gouv.ml",
                "notes": "Station limnimétrique repère de Koulikoro Gare (navigation fluviale COMANAV).",
            },
            {
                "region_code": "KOU",
                "directorate_type": "DREF",
                "name": "Direction Régionale des Eaux et Forêts de Koulikoro",
                "address": "Route de Banamba, Koulikoro",
                "latitude": 12.8650,
                "longitude": -7.5510,
                "phone_primary": "+223 21 26 22 45",
                "phone_secondary": "+223 21 26 27 12",
                "emergency_number": "122",
                "email": "dref.koulikoro@eaux-forets.gouv.ml",
                "notes": "Protection des réserves du Baoulé et lutte contre la carbonisation.",
            },
            {
                "region_code": "KOU",
                "directorate_type": "DRACPN",
                "name": "Direction Régionale de l'Assainissement et du Contrôle des Pollutions et des Nuisances de Koulikoro",
                "address": "Koulikoro Gare, face mairie",
                "latitude": 12.8600,
                "longitude": -7.5610,
                "phone_primary": "+223 21 26 24 15",
                "phone_secondary": "+223 21 26 24 18",
                "emergency_number": "122",
                "email": "dracpn.koulikoro@environnement.gouv.ml",
                "notes": "Contrôle des dragues aurifères et des effluents industriels du fleuve.",
            },
            {
                "region_code": "KOU",
                "directorate_type": "DRA",
                "name": "Direction Régionale de l'Agriculture de Koulikoro",
                "address": "Plateau Administratif, Koulikoro",
                "latitude": 12.8615,
                "longitude": -7.5560,
                "phone_primary": "+223 21 26 20 80",
                "phone_secondary": "+223 21 26 26 30",
                "emergency_number": "122",
                "email": "dra.koulikoro@agriculture.gouv.ml",
                "notes": "Surveillance agro-écologique de la zone de savane soudanienne nord.",
            },

            # ── GAO ──
            {
                "region_code": "GAO",
                "directorate_type": "DRPC",
                "name": "Direction Régionale de la Protection Civile de Gao",
                "address": "Quartier Château d'eau, Gao",
                "latitude": 16.2760,
                "longitude": -0.0410,
                "phone_primary": "+223 21 82 04 22",
                "phone_secondary": "+223 21 82 05 22",
                "emergency_number": "122",
                "email": "drpc.gao@protectioncivile.gouv.ml",
                "notes": "Secours et résilience face aux tempêtes de sable et crues soudaines du fleuve.",
            },
            {
                "region_code": "GAO",
                "directorate_type": "DRH",
                "name": "Direction Régionale de l'Hydraulique de Gao",
                "address": "Quartier Sosso Koïra, Gao",
                "latitude": 16.2680,
                "longitude": -0.0490,
                "phone_primary": "+223 21 82 06 15",
                "phone_secondary": "+223 21 82 08 20",
                "emergency_number": "122",
                "email": "drh.gao@hydraulique.gouv.ml",
                "notes": "Surveillance du bief sahélien du fleuve Niger et des mares pastorales.",
            },
            {
                "region_code": "GAO",
                "directorate_type": "DREF",
                "name": "Direction Régionale des Eaux et Forêts de Gao",
                "address": "Boulevard des Askia, Gao",
                "latitude": 16.2730,
                "longitude": -0.0430,
                "phone_primary": "+223 21 82 03 55",
                "phone_secondary": "+223 21 82 07 10",
                "emergency_number": "122",
                "email": "dref.gao@eaux-forets.gouv.ml",
                "notes": "Lutte contre l'ensablement des berges du fleuve et fixations des dunes.",
            },
            {
                "region_code": "GAO",
                "directorate_type": "DRACPN",
                "name": "Direction Régionale de l'Assainissement et du Contrôle des Pollutions et des Nuisances de Gao",
                "address": "Quartier Aljanabandia, Gao",
                "latitude": 16.2690,
                "longitude": -0.0460,
                "phone_primary": "+223 21 82 07 40",
                "phone_secondary": "+223 21 82 07 42",
                "emergency_number": "122",
                "email": "dracpn.gao@environnement.gouv.ml",
                "notes": "Gestion de l'assainissement urbain et des déchets en milieu aride.",
            },
            {
                "region_code": "GAO",
                "directorate_type": "DRA",
                "name": "Direction Régionale de l'Agriculture de Gao",
                "address": "Quartier Château d'eau, Gao",
                "latitude": 16.2740,
                "longitude": -0.0420,
                "phone_primary": "+223 21 82 02 70",
                "phone_secondary": "+223 21 82 05 90",
                "emergency_number": "122",
                "email": "dra.gao@agriculture.gouv.ml",
                "notes": "Surveillance des cultures irriguées du fleuve et alerte antiacridienne.",
            },

            # ── PROTECTION CIVILE (DRPC - 122) POUR TOUTES LES AUTRES RÉGIONS ──
            {
                "region_code": "TOM",
                "directorate_type": "DRPC",
                "name": "Direction Régionale de la Protection Civile de Tombouctou",
                "address": "Quartier Sankoré / Abaradjou, Tombouctou",
                "latitude": 16.7720,
                "longitude": -3.0060,
                "phone_primary": "+223 21 92 11 22",
                "emergency_number": "122",
                "email": "drpc.tombouctou@protectioncivile.gouv.ml",
                "notes": "Vigilance crues et canicules au seuil du Sahara.",
            },
            {
                "region_code": "KID",
                "directorate_type": "DRPC",
                "name": "Direction Régionale de la Protection Civile de Kidal",
                "address": "Quartier Administratif, Kidal",
                "latitude": 18.4450,
                "longitude": 1.4110,
                "phone_primary": "+223 21 85 01 22",
                "emergency_number": "122",
                "email": "drpc.kidal@protectioncivile.gouv.ml",
                "notes": "Coordination des secours et résilience en milieu désertique extrême.",
            },
            {
                "region_code": "TAO",
                "directorate_type": "DRPC",
                "name": "Direction Régionale de la Protection Civile de Taoudénit",
                "address": "Siège Régional Administratif, Taoudénit",
                "latitude": 22.6780,
                "longitude": -3.9810,
                "phone_primary": "+223 21 92 20 22",
                "emergency_number": "122",
                "email": "drpc.taoudenit@protectioncivile.gouv.ml",
                "notes": "Gestion des secours d'urgence grand nord désertique.",
            },
            {
                "region_code": "MEN",
                "directorate_type": "DRPC",
                "name": "Direction Régionale de la Protection Civile de Ménaka",
                "address": "Quartier Administratif, Ménaka",
                "latitude": 15.9210,
                "longitude": 2.4050,
                "phone_primary": "+223 21 83 01 22",
                "emergency_number": "122",
                "email": "drpc.menaka@protectioncivile.gouv.ml",
                "notes": "Protection civile et alertes pastorales régionales.",
            },
            {
                "region_code": "NIO",
                "directorate_type": "DRPC",
                "name": "Direction Régionale de la Protection Civile de Nioro du Sahel",
                "address": "Quartier Diaka, Nioro",
                "latitude": 15.2310,
                "longitude": -9.5860,
                "phone_primary": "+223 21 54 01 22",
                "emergency_number": "122",
                "email": "drpc.nioro@protectioncivile.gouv.ml",
                "notes": "Surveillance des crues d'oueds et feux de brousse sahéliens.",
            },
            {
                "region_code": "KIT",
                "directorate_type": "DRPC",
                "name": "Direction Régionale de la Protection Civile de Kita",
                "address": "Quartier Moribabougou, Kita",
                "latitude": 13.0380,
                "longitude": -9.4860,
                "phone_primary": "+223 21 57 01 22",
                "emergency_number": "122",
                "email": "drpc.kita@protectioncivile.gouv.ml",
                "notes": "Protection civile du bassin supérieur du Bakoye.",
            },
            {
                "region_code": "DIO",
                "directorate_type": "DRPC",
                "name": "Direction Régionale de la Protection Civile de Dioïla",
                "address": "Quartier Administratif, Dioïla",
                "latitude": 12.4960,
                "longitude": -6.7940,
                "phone_primary": "+223 21 27 01 22",
                "emergency_number": "122",
                "email": "drpc.dioila@protectioncivile.gouv.ml",
                "notes": "Surveillance des crues du Bagoé et zones cotonnières.",
            },
            {
                "region_code": "NAR",
                "directorate_type": "DRPC",
                "name": "Direction Régionale de la Protection Civile de Nara",
                "address": "Quartier Gare, Nara",
                "latitude": 15.1720,
                "longitude": -7.2830,
                "phone_primary": "+223 21 29 01 22",
                "emergency_number": "122",
                "email": "drpc.nara@protectioncivile.gouv.ml",
                "notes": "Surveillance des feux pastoraux et stress hydrique sahélien.",
            },
            {
                "region_code": "BOU",
                "directorate_type": "DRPC",
                "name": "Direction Régionale de la Protection Civile de Bougouni",
                "address": "Quartier Massablacoro, Bougouni",
                "latitude": 11.4210,
                "longitude": -7.4800,
                "phone_primary": "+223 21 65 01 22",
                "emergency_number": "122",
                "email": "drpc.bougouni@protectioncivile.gouv.ml",
                "notes": "Surveillance du bassin du Baoulé et massif forestier sud.",
            },
            {
                "region_code": "KTL",
                "directorate_type": "DRPC",
                "name": "Direction Régionale de la Protection Civile de Koutiala",
                "address": "Quartier Darsalam, Koutiala",
                "latitude": 12.3950,
                "longitude": -5.4610,
                "phone_primary": "+223 21 64 01 22",
                "emergency_number": "122",
                "email": "drpc.koutiala@protectioncivile.gouv.ml",
                "notes": "Secours et prévention des risques industriels et agricoles.",
            },
            {
                "region_code": "SAN",
                "directorate_type": "DRPC",
                "name": "Direction Régionale de la Protection Civile de San",
                "address": "Quartier Santoro, San",
                "latitude": 13.3060,
                "longitude": -4.8920,
                "phone_primary": "+223 21 37 01 22",
                "emergency_number": "122",
                "email": "drpc.san@protectioncivile.gouv.ml",
                "notes": "Surveillance des crues de la plaine du Bani et du Sanké.",
            },
            {
                "region_code": "DOU",
                "directorate_type": "DRPC",
                "name": "Direction Régionale de la Protection Civile de Douentza",
                "address": "Quartier Administratif, Douentza",
                "latitude": 14.9990,
                "longitude": -2.9460,
                "phone_primary": "+223 21 45 01 22",
                "emergency_number": "122",
                "email": "drpc.douentza@protectioncivile.gouv.ml",
                "notes": "Secours au piémont des falaises et résilience pastorale.",
            },
            {
                "region_code": "BAN",
                "directorate_type": "DRPC",
                "name": "Direction Régionale de la Protection Civile de Bandiagara",
                "address": "Quartier Soroly, Bandiagara",
                "latitude": 14.3530,
                "longitude": -3.6070,
                "phone_primary": "+223 21 44 01 22",
                "emergency_number": "122",
                "email": "drpc.bandiagara@protectioncivile.gouv.ml",
                "notes": "Interventions en relief escarpé du Pays Dogon et falaises.",
            },
        ]

        created_dirs_count = 0
        updated_dirs_count = 0

        for d_data in directorates_catalog:
            reg_code = d_data.pop("region_code")
            reg = regions_by_code.get(reg_code)
            if not reg:
                continue

            obj, created = RegionalDirectorate.objects.update_or_create(
                region=reg,
                directorate_type=d_data["directorate_type"],
                name=d_data["name"],
                defaults={
                    "address": d_data.get("address", ""),
                    "latitude": d_data["latitude"],
                    "longitude": d_data["longitude"],
                    "phone_primary": d_data["phone_primary"],
                    "phone_secondary": d_data.get("phone_secondary", ""),
                    "emergency_number": d_data.get("emergency_number", "122"),
                    "email": d_data.get("email", ""),
                    "is_active": True,
                    "notes": d_data.get("notes", ""),
                }
            )
            if created:
                created_dirs_count += 1
            else:
                updated_dirs_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"-> {created_dirs_count} directions régionales créées, {updated_dirs_count} actualisées."
            )
        )

        # 3. Lier chaque zone à sa région et s'assurer que les directions régionales sont associées
        zones = MonitoringZone.objects.all()
        for zone in zones:
            if not zone.region:
                # Find best matching region
                match_reg = None
                for r in Region.objects.all():
                    if r.name.lower() in zone.name.lower():
                        match_reg = r
                        break
                if not match_reg:
                    match_reg = regions_by_code.get("BKO")
                zone.region = match_reg
                zone.save()

            # Associate competent directorates
            reg_dirs = zone.region.directorates.filter(is_active=True)
            if reg_dirs.exists():
                zone.competent_directorates.set(reg_dirs)

        self.stdout.write(
            self.style.SUCCESS(f"-> {zones.count()} zones de surveillance reliées avec succès à leurs directions.")
        )
        self.stdout.write(self.style.SUCCESS("=== SEEDING RÉGIONS & DIRECTIONS RÉGIONALES TERMINÉ AVEC SUCCÈS ==="))
