# Generated by Django 4.2.30 on 2026-08-17 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('detected_at', models.DateTimeField()),
                ('satellite', models.CharField(blank=True, default='MODIS', max_length=64)),
                ('confidence', models.CharField(blank=True, default='nominal', max_length=20)),
                ('brightness', models.FloatField(blank=True, null=True)),
                ('frp', models.FloatField(blank=True, help_text='Fire Radiative Power', null=True)),
                ('scan', models.FloatField(blank=True, null=True)),
                ('track', models.FloatField(blank=True, null=True)),
                ('bright_t31', models.FloatField(blank=True, null=True)),
                ('daynight', models.CharField(blank=True, default='D', max_length=10)),
                ('source', models.CharField(blank=True, default='NASA FIRMS', max_length=128)),
                ('is_simulated', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fires', to='geography.monitoringzone')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['-detected_at'], name='fires_fired_detecte_e7a15f_idx'), models.Index(fields=['latitude', 'longitude'], name='fires_fired_latitud_6e02df_idx')],
            },
        ),
    ]
