# Generated by Django 4.2.30 on 2026-08-17 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtmosphericObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(choices=[('NO2', 'NO₂'), ('SO2', 'SO₂'), ('CO', 'CO'), ('CH4', 'CH₄'), ('O3', 'O₃'), ('AEROSOLS', 'Aérosols'), ('PM25', 'PM2.5'), ('PM10', 'PM10')], max_length=32)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('baseline_value', models.FloatField(blank=True, null=True)),
                ('std_dev', models.FloatField(blank=True, null=True)),
                ('observed_at', models.DateTimeField()),
                ('source', models.CharField(default='Sentinel-5P', max_length=128)),
                ('quality_flag', models.CharField(blank=True, default='GOOD', max_length=32)),
                ('is_simulated', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atmospheric_observations', to='geography.monitoringzone')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['zone', 'variable', '-observed_at'], name='atmosphere__zone_id_e88a8b_idx')],
            },
        ),
    ]
