# Generated by Django 4.2.30 on 2026-08-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=128)),
                ('source_type', models.CharField(choices=[('SATELLITE', 'Satellite'), ('CLIMATE', 'Climat'), ('ATMOSPHERE', 'Atmosphère'), ('FIRE', 'Feu'), ('WATER', 'Eau'), ('SENSOR', 'Capteur'), ('AI', 'IA')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_simulated', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEGRADED', 'Dégradée'), ('OFFLINE', 'Hors ligne'), ('NOT_CONFIGURED', 'Non configurée')], default='NOT_CONFIGURED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
