# Generated by Django 4.2.30 on 2026-08-17 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body_type', models.CharField(choices=[('RIVER', 'Rivière'), ('LAKE', 'Lac'), ('RESERVOIR', 'Réservoir'), ('POND', 'Mare'), ('DAM', 'Barrage')], max_length=32)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('area_km2', models.FloatField(blank=True, null=True)),
                ('is_simulated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='water_bodies', to='geography.monitoringzone')),
            ],
        ),
        migrations.CreateModel(
            name='WaterObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('TEMPERATURE', 'Température'), ('PH', 'pH'), ('TURBIDITY', 'Turbidité'), ('CONDUCTIVITY', 'Conductivité'), ('DISSOLVED_OXYGEN', 'Oxygène dissous'), ('WATER_LEVEL', "Niveau d'eau")], max_length=32)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('baseline_value', models.FloatField(blank=True, null=True)),
                ('std_dev', models.FloatField(blank=True, null=True)),
                ('measured_at', models.DateTimeField()),
                ('source', models.CharField(default='Sensor', max_length=128)),
                ('is_simulated', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('water_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='water.waterbody')),
            ],
            options={
                'ordering': ['-measured_at'],
                'indexes': [models.Index(fields=['water_body', 'metric', '-measured_at'], name='water_water_water_b_969ff8_idx')],
            },
        ),
    ]
