# Generated by Django 4.2.30 on 2026-08-24 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydrologicalStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('cours_d_eau', models.CharField(default='Niger', max_length=64)),
                ('latitude', models.FloatField(help_text='Latitude administrative / géographique')),
                ('longitude', models.FloatField(help_text='Longitude administrative / géographique')),
                ('latitude_river', models.FloatField(blank=True, help_text='Latitude recalée sur chenal GloFAS', null=True)),
                ('longitude_river', models.FloatField(blank=True, help_text='Longitude recalée sur chenal GloFAS', null=True)),
                ('seuil_vigilance', models.FloatField(default=1000.0, help_text='Débit seuil de vigilance (m3/s)')),
                ('seuil_alerte', models.FloatField(default=2000.0, help_text="Débit seuil d'alerte crue (m3/s)")),
                ('seuil_danger', models.FloatField(default=3000.0, help_text='Débit seuil de danger imminent (m3/s)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hydrological_stations', to='geography.monitoringzone')),
            ],
            options={
                'verbose_name': 'Station hydrologique',
                'verbose_name_plural': 'Stations hydrologiques',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='RiverForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_run', models.DateField(help_text='Date du run opérationnel GloFAS')),
                ('leadtime_hours', models.IntegerField(help_text='Échéance de prévision (24, 48, 72)')),
                ('discharge_m3s', models.FloatField(help_text='Débit prévu en m3/s')),
                ('trend_72h_pct', models.FloatField(default=0.0, help_text='Pourcentage de variation de tendance à 72h')),
                ('alert_level', models.CharField(choices=[('GREEN', 'Normal / Vert'), ('YELLOW', 'Vigilance / Jaune'), ('ORANGE', 'Alerte / Orange'), ('RED', 'Danger / Rouge')], default='GREEN', max_length=16)),
                ('is_simulated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='water.hydrologicalstation')),
            ],
            options={
                'verbose_name': 'Prévision de débit',
                'verbose_name_plural': 'Prévisions de débit',
                'ordering': ['-date_run', 'station', 'leadtime_hours'],
                'indexes': [models.Index(fields=['station', '-date_run', 'leadtime_hours'], name='water_river_station_7f4643_idx'), models.Index(fields=['alert_level'], name='water_river_alert_l_5db740_idx')],
            },
        ),
        migrations.CreateModel(
            name='FloodObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile_name', models.CharField(help_text='Tuile MODAPS ex: h16v07, h17v07', max_length=32)),
                ('observation_date', models.DateField(help_text="Date d'observation satellitaire")),
                ('flooded_area_km2', models.FloatField(default=0.0, help_text='Superficie inondée totale en km2')),
                ('flooded_pixels_count', models.IntegerField(default=0, help_text='Nombre de pixels inondés (classe 3)')),
                ('flood_geojson', models.JSONField(blank=True, default=dict, help_text='GeoJSON FeatureCollection des centroïdes / emprises')),
                ('source', models.CharField(default='NASA LANCE VIIRS', max_length=128)),
                ('is_simulated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flood_observations', to='geography.monitoringzone')),
            ],
            options={
                'verbose_name': "Observation d'inondation",
                'verbose_name_plural': "Observations d'inondation",
                'ordering': ['-observation_date', 'tile_name'],
                'indexes': [models.Index(fields=['-observation_date', 'tile_name'], name='water_flood_observa_694ca8_idx')],
            },
        ),
    ]
