# Generated by Django 4.2.30 on 2026-09-16 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['region_number', 'name'], 'verbose_name': 'Région Administrative', 'verbose_name_plural': 'Régions Administratives'},
        ),
        migrations.AddField(
            model_name='region',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude du chef-lieu', null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude du chef-lieu', null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='region_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Numéro officiel selon la loi de découpage administratif 2023 (1 à 19, ou 0 pour Bamako)', null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='capital',
            field=models.CharField(blank=True, help_text='Chef-lieu de la région', max_length=255),
        ),
        migrations.CreateModel(
            name='RegionalDirectorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directorate_type', models.CharField(choices=[('DRPC', 'Direction Régionale de la Protection Civile'), ('DRH', "Direction Régionale de l'Hydraulique"), ('DREF', 'Direction Régionale des Eaux et Forêts'), ('DRACPN', "Direction Régionale de l'Assainissement et du Contrôle des Pollutions et des Nuisances"), ('DRA', "Direction Régionale de l'Agriculture"), ('OTHER', 'Autre Direction Régionale')], default='DRPC', help_text="Spécialité ou domaine d'intervention", max_length=20)),
                ('name', models.CharField(help_text='Nom officiel du service régional', max_length=255)),
                ('address', models.CharField(blank=True, help_text='Adresse ou quartier du siège régional', max_length=255)),
                ('latitude', models.FloatField(help_text='Position GPS Latitude du siège')),
                ('longitude', models.FloatField(help_text='Position GPS Longitude du siège')),
                ('phone_primary', models.CharField(help_text='Ligne téléphonique standard', max_length=64)),
                ('phone_secondary', models.CharField(blank=True, help_text='Ligne secondaire ou astreinte', max_length=64)),
                ('emergency_number', models.CharField(default='122', help_text="Numéro d'urgence rapide (ex: 122)", max_length=32)),
                ('email', models.EmailField(blank=True, help_text='Courriel officiel', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text="Actif dans le plan de surveillance et d'alerte")),
                ('notes', models.TextField(blank=True, help_text='Informations opérationnelles complémentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(help_text='Région administrative de compétence', on_delete=django.db.models.deletion.CASCADE, related_name='directorates', to='geography.region')),
            ],
            options={
                'verbose_name': 'Direction Régionale',
                'verbose_name_plural': 'Directions Régionales',
                'ordering': ['region', 'directorate_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='monitoringzone',
            name='competent_directorates',
            field=models.ManyToManyField(blank=True, help_text='Directions spécifiques assignées à cette zone en plus des directions régionales', related_name='assigned_zones', to='geography.regionaldirectorate'),
        ),
    ]
