# Generated by Django 4.2.30 on 2026-08-17 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IEZCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, help_text='0-100')),
                ('status', models.CharField(choices=[('BON', 'Bon état'), ('VIGILANCE', 'Vigilance'), ('DEGRADÉ', 'Dégradé'), ('CRITIQUE', 'Critique')], default='DEGRADÉ', max_length=20)),
                ('components', models.JSONField(blank=True, default=dict)),
                ('weights', models.JSONField(blank=True, default=dict)),
                ('algorithm_version', models.CharField(default='1.0', max_length=32)),
                ('calculated_at', models.DateTimeField()),
                ('is_simulated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iez_calculations', to='geography.monitoringzone')),
            ],
            options={
                'verbose_name': 'Calcul IEZ',
                'verbose_name_plural': 'Calculs IEZ',
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['zone', '-calculated_at'], name='iez_iezcalc_zone_id_6a5e21_idx')],
            },
        ),
    ]
