# Generated by Django 4.2.30 on 2026-08-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='Latitude WGS84')),
                ('longitude', models.FloatField(help_text='Longitude WGS84')),
                ('report_type', models.CharField(choices=[('FLOOD', 'Inondation / Crue'), ('WILDFIRE', 'Feu de brousse / Incendie'), ('DROUGHT', 'Sécheresse / Puits tari'), ('WATER_QUALITY', 'Pollution eau / Fleuve'), ('OTHER', 'Autre anomalie écologique')], default='OTHER', max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Modéré'), ('HIGH', 'Élevé'), ('CRITICAL', 'Urgence critique')], default='MEDIUM', max_length=20)),
                ('title', models.CharField(help_text="Titre court de l'observation", max_length=150)),
                ('description', models.TextField(help_text='Détail du constat terrain')),
                ('author_name', models.CharField(default='Anonyme', help_text="Nom de l'observateur ou agent", max_length=100)),
                ('author_phone', models.CharField(blank=True, default='', help_text='Contact téléphonique optionnel', max_length=30)),
                ('is_verified', models.BooleanField(default=False, help_text='Validation par un expert ou modérateur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Signalement Terrain',
                'verbose_name_plural': 'Signalements Terrain',
                'ordering': ['-created_at'],
            },
        ),
    ]
