# Generated by Django 4.2.30 on 2026-08-17 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('VEGETATION', 'Végétation'), ('WATER', 'Eau'), ('FIRE', 'Feu'), ('CLIMATE', 'Climat'), ('ATMOSPHERE', 'Atmosphère'), ('MULTI_SIGNAL', 'Multi-signal')], max_length=32)),
                ('source', models.CharField(max_length=128)),
                ('detected_at', models.DateTimeField()),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé'), ('CRITICAL', 'Critique')], default='LOW', max_length=20)),
                ('score', models.FloatField(default=0.0, help_text='0-100 anomaly score')),
                ('confidence', models.FloatField(default=0.0, help_text='0-1 confidence')),
                ('metric', models.CharField(blank=True, max_length=128)),
                ('current_value', models.FloatField(blank=True, null=True)),
                ('baseline_value', models.FloatField(blank=True, null=True)),
                ('z_score', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'Nouveau'), ('INVESTIGATING', "En cours d'investigation"), ('CONFIRMED', 'Confirmé'), ('RESOLVED', 'Résolu'), ('DISMISSED', 'Rejeté')], default='NEW', max_length=20)),
                ('is_simulated', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='geography.monitoringzone')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['-detected_at'], name='anomalies_a_detecte_b8ac4a_idx'), models.Index(fields=['zone', 'anomaly_type'], name='anomalies_a_zone_id_bc83be_idx')],
            },
        ),
    ]
