# Generated by Django 4.2.30 on 2026-08-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('category', models.CharField(choices=[('NEWS', 'Actualités'), ('ECOLOGY', 'Écologie & Biodiversité'), ('FLOOD_ALERT', 'Alerte Inondation'), ('INNOVATION', 'Innovation & Tech')], default='NEWS', max_length=50, verbose_name='Catégorie')),
                ('summary', models.TextField(verbose_name='Résumé / Accroche')),
                ('content', models.TextField(verbose_name='Contenu complet')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cms/blog/', verbose_name='Image de couverture')),
                ('cover_image_url', models.URLField(blank=True, default='', max_length=500, verbose_name='URL Image externe')),
                ('author_name', models.CharField(default='Équipe ECO-SURVEILLANCE', max_length=100, verbose_name='Auteur')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publié')], default='PUBLISHED', max_length=20, verbose_name='Statut')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Vues')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article de Blog',
                'verbose_name_plural': 'Articles de Blog',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titre du projet')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('subtitle', models.CharField(blank=True, default='', max_length=250, verbose_name='Sous-titre')),
                ('category', models.CharField(choices=[('SURVEILLANCE', 'Surveillance Spatiale'), ('HYDROLOGIE', 'Modélisation Hydrologique'), ('AI_PREDICTION', 'Intelligence Artificielle & IA'), ('COMMUNAUTE', 'Alerte & Mobilisation'), ('BIODIVERSITE', 'Biodiversité & Forêts')], default='SURVEILLANCE', max_length=100, verbose_name='Catégorie')),
                ('description', models.TextField(verbose_name='Description du projet')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cms/portfolio/', verbose_name='Image de couverture')),
                ('cover_image_url', models.URLField(blank=True, default='', max_length=500, verbose_name='URL Image externe')),
                ('partner_or_client', models.CharField(blank=True, default='', max_length=200, verbose_name='Partenaire / Client')),
                ('technologies_used', models.CharField(default='Google Earth Engine, Sentinel-2, GloFAS, Django, Leaflet', max_length=250, verbose_name='Technologies utilisées')),
                ('demo_url', models.URLField(blank=True, default='', max_length=500, verbose_name='Lien Démo / En savoir plus')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Projet mis en avant')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Date de finalisation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Projet Réalisé',
                'verbose_name_plural': 'Portfolio Projets',
                'ordering': ['-is_featured', '-completion_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ECO-SURVEILLANCE MALI', max_length=150, verbose_name='Nom de la plateforme')),
                ('site_tagline', models.CharField(default='Plateforme Nationale de Surveillance Environnementale & Hydrologique', max_length=255, verbose_name='Slogan / Sous-titre')),
                ('contact_email', models.EmailField(default='contact@eco-surveillance.ml', max_length=254, verbose_name='Email de contact')),
                ('contact_phone', models.CharField(default='+223 20 22 00 00', max_length=50, verbose_name='Téléphone fixe')),
                ('whatsapp_phone', models.CharField(default='+223 70 00 00 00', max_length=50, verbose_name='WhatsApp')),
                ('emergency_line', models.CharField(default='80 00 11 22', max_length=50, verbose_name="Numéro d'urgence vert")),
                ('headquarters_address', models.CharField(default='Bamako, Mali — Cité Administrative, Bâtiment Numérique', max_length=255, verbose_name='Adresse du siège')),
                ('facebook_url', models.URLField(blank=True, default='', max_length=255, verbose_name='Facebook')),
                ('twitter_url', models.URLField(blank=True, default='', max_length=255, verbose_name='X / Twitter')),
                ('linkedin_url', models.URLField(blank=True, default='', max_length=255, verbose_name='LinkedIn')),
                ('github_url', models.URLField(blank=True, default='', max_length=255, verbose_name='GitHub')),
                ('alert_banner_active', models.BooleanField(default=False, verbose_name="Activer le bandeau d'alerte national")),
                ('alert_banner_text', models.CharField(blank=True, default='', max_length=300, verbose_name='Texte du bandeau')),
                ('alert_banner_level', models.CharField(choices=[('INFO', 'Information (Bleu)'), ('WARNING', 'Vigilance (Jaune/Orange)'), ('DANGER', 'Danger / Alerte (Rouge)'), ('CRITICAL', 'Urgence Absolue (Violet/Noir)')], default='WARNING', max_length=20, verbose_name='Niveau de gravité du bandeau')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres du Site',
                'verbose_name_plural': 'Paramètres du Site',
            },
        ),
    ]
