# Generated by Django 4.2.30 on 2026-08-17 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VegetationObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_name', models.CharField(choices=[('NDVI', 'NDVI'), ('NDWI', 'NDWI'), ('EVI', 'EVI'), ('SAVI', 'SAVI')], default='NDVI', max_length=16)),
                ('value', models.FloatField()),
                ('baseline_value', models.FloatField(blank=True, null=True)),
                ('std_dev', models.FloatField(blank=True, null=True)),
                ('acquisition_date', models.DateField()),
                ('source', models.CharField(default='Sentinel-2', max_length=128)),
                ('is_simulated', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vegetation_observations', to='geography.monitoringzone')),
            ],
            options={
                'ordering': ['-acquisition_date'],
                'indexes': [models.Index(fields=['zone', 'index_name', '-acquisition_date'], name='vegetation__zone_id_49f699_idx')],
            },
        ),
    ]
