# Generated by Django 4.2.30 on 2026-08-17 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type', models.CharField(choices=[('WILDFIRE', 'Feu de forêt'), ('DROUGHT', 'Sécheresse'), ('VEGETATION_DEGRADATION', 'Dégradation végétale'), ('WATER_POLLUTION', 'Pollution eau'), ('WATER_STRESS', 'Stress hydrique'), ('ATMOSPHERIC_ANOMALY', 'Anomalie atmosphérique'), ('HEAT', 'Canicule'), ('ENVIRONMENTAL_GENERAL', 'Risque général')], max_length=32)),
                ('risk_score', models.FloatField(default=0.0, help_text='0-100')),
                ('confidence_score', models.FloatField(default=0.0, help_text='0-100')),
                ('level', models.CharField(choices=[('GREEN', 'Normal'), ('YELLOW', 'Vigilance'), ('ORANGE', 'Risque élevé'), ('RED', 'Danger critique')], default='GREEN', max_length=16)),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé'), ('CRITICAL', 'Critique')], default='LOW', max_length=20)),
                ('factors', models.JSONField(blank=True, default=list)),
                ('algorithm_version', models.CharField(default='1.0', max_length=32)),
                ('calculated_at', models.DateTimeField()),
                ('is_simulated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='geography.monitoringzone')),
            ],
            options={
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['zone', 'risk_type', '-calculated_at'], name='risk_riskas_zone_id_16d741_idx')],
            },
        ),
    ]
