# Generated by Django 4.2.30 on 2026-08-17 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anomalies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('incident_type', models.CharField(choices=[('WILDFIRE', 'Feu de forêt'), ('DROUGHT', 'Sécheresse'), ('VEGETATION_DEGRADATION', 'Dégradation végétale'), ('WATER_POLLUTION', 'Pollution eau'), ('WATER_STRESS', 'Stress hydrique'), ('ATMOSPHERIC_ANOMALY', 'Anomalie atmosphérique'), ('HEAT', 'Canicule'), ('GENERAL', 'Général')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé'), ('CRITICAL', 'Critique')], default='LOW', max_length=20)),
                ('risk_score', models.FloatField(default=0.0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('source', models.CharField(blank=True, max_length=128)),
                ('detected_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('NEW', 'Nouveau'), ('INVESTIGATING', 'En cours'), ('CONFIRMED', 'Confirmé'), ('RESOLVED', 'Résolu'), ('DISMISSED', 'Rejeté')], default='NEW', max_length=20)),
                ('is_simulated', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anomaly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='anomalies.anomaly')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
