# Generated by Django 4.2.30 on 2026-08-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('WILDFIRE', 'Feu de forêt'), ('DROUGHT', 'Sécheresse'), ('FLOOD', 'Inondation / Crue'), ('VEGETATION_DEGRADATION', 'Dégradation végétale'), ('WATER_POLLUTION', 'Pollution eau'), ('WATER_STRESS', 'Stress hydrique'), ('ATMOSPHERIC_ANOMALY', 'Anomalie atmosphérique'), ('HEAT', 'Canicule'), ('GENERAL', 'Général')], max_length=32),
        ),
    ]
